# Generated by Django 4.2.16 on 2024-11-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=512)),
                ('urlImg', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conocimiento', models.CharField(max_length=15)),
                ('nivel', models.IntegerField()),
                ('grupo_conocimiento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Portafolio_Web.grupoconocimiento')),
            ],
        ),
    ]
